<script setup lang="ts">
import { ref, computed  } from 'vue';
import DataTable from 'datatables.net-vue3';
import DataTablesCore from 'datatables.net-dt';
import 'datatables.net-dt/css/dataTables.dataTables.css';
import { Link,usePage } from '@inertiajs/vue3';


const page = usePage();

// auth users  
const auth = computed(() => page.props.auth);

const role = computed(() => page.props.auth.role);


DataTable.use(DataTablesCore);

defineOptions({
    layout: {
        breadcrumbs: [
            {
                title: 'Dashboard',
                href: '/dashboard',
            },
        ],
    },
});

const props = defineProps<{
    shortUrls: {
        data: any[];
        links: any[];
        current_page: number;
        last_page: number;
        total: number;
    };
}>();


const columns = [
    {
        data: null,
        title: 'S.No',
        orderable: false,
        searchable: false,
        render: (data: any, type: any, row: any, meta: any) => {
            return (
                (props.shortUrls.current_page - 1) * props.shortUrls.per_page +
                meta.row +
                1
            );
        },
    },
    { data: 'original_url', title: 'Original Url' },
    {
        data: 'short_url',
        title: 'Short Url',
        orderable: false,
        searchable: false,
        render: (data: any, type: any, row: any, meta: any) => {
            const shortUrl = `${window.location.origin}/company/s/${row.short_url}`;
             return `
                    <a
                        href="${shortUrl}"
                        target="_blank"
                        rel="noopener noreferrer"
                        title="View Short URL"
                        class="text-blue-600 hover:underline"
                    >
                        ${shortUrl}
                    </a>
                `;
        },
    
    },
];

if (['SuperAdmin', 'Admin'].includes(role.value)) {
    columns.push(
        {
            data: 'name',
            title: 'Generated By',
        },
        {
            data: 'company_name',
            title: 'Company Name',
        }
    );
}

</script>

<template>
    <div class="p-6">
        <h1 class="text-xl font-bold mb-4">Dashboard <p> You are default Login as role <span class="text-blue-600">{{ auth.role }}</span> of Company <span class="text-blue-600">{{ auth.owned_company.name }}</span></p></h1>

        <DataTable
            :data="shortUrls.data"
            :columns="columns"
            :options="{
                paging: false,
                searching: false,
                info: false
            }"
            class="display"
        />

       <div v-if="shortUrls.links.length > 3" class="flex flex-wrap justify-end mt-6">
            <template v-for="(link, key) in shortUrls.links" :key="key">
                <div 
                    v-if="link.url === null" 
                    class="mr-1 mb-1 px-4 py-2 text-sm leading-4 text-gray-400 border rounded"
                    v-html="link.label" 
                />
                
                <Link 
                    v-else 
                    class="mr-1 mb-1 px-4 py-2 text-sm leading-4 border rounded hover:bg-gray-100 focus:border-indigo-500"
                    :class="{ 'bg-blue-600 text-white border-blue-600 hover:bg-blue-700': link.active }"
                    :href="link.url" 
                    v-html="link.label" 
                />
                
            </template>
        </div>
    </div>

</template>
